# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Converter.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon


class Ui_ConverterWidget(object):
    def setupUi(self, ConverterWidget):
        ConverterWidget.setObjectName("ConverterWidget")
        ConverterWidget.resize(754, 223)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ConverterWidget.sizePolicy().hasHeightForWidth())
        ConverterWidget.setSizePolicy(sizePolicy)
        ConverterWidget.setMinimumSize(QtCore.QSize(754, 223))
        ConverterWidget.setMaximumSize(QtCore.QSize(754, 223))
        self.gridLayoutWidget = QtWidgets.QWidget(ConverterWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 30, 691, 161))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cbFromCurrency = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cbFromCurrency.setObjectName("cbFromCurrency")
        self.horizontalLayout_2.addWidget(self.cbFromCurrency)
        self.tfFromCurrency = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tfFromCurrency.sizePolicy().hasHeightForWidth())
        self.tfFromCurrency.setSizePolicy(sizePolicy)
        self.tfFromCurrency.setMaximum(99999999.99)
        self.tfFromCurrency.setObjectName("tfFromCurrency")
        self.horizontalLayout_2.addWidget(self.tfFromCurrency)
        self.btSwap = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btSwap.setText("")
        self.btSwap.setObjectName("btSwap")
        self.horizontalLayout_2.addWidget(self.btSwap)
        self.cbToCurrency = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cbToCurrency.setObjectName("cbToCurrency")
        self.horizontalLayout_2.addWidget(self.cbToCurrency)
        self.tfConvertResult = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.tfConvertResult.setReadOnly(True)
        self.tfConvertResult.setObjectName("tfConvertResult")
        self.horizontalLayout_2.addWidget(self.tfConvertResult)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 4)
        self.btShowTable = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btShowTable.sizePolicy().hasHeightForWidth())
        self.btShowTable.setSizePolicy(sizePolicy)
        self.btShowTable.setObjectName("btShowTable")
        self.gridLayout_2.addWidget(self.btShowTable, 1, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 2)
        self.btRefresh = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btRefresh.sizePolicy().hasHeightForWidth())
        self.btRefresh.setSizePolicy(sizePolicy)
        self.btRefresh.setObjectName("btRefresh")
        self.gridLayout_2.addWidget(self.btRefresh, 1, 2, 1, 1)

        self.retranslateUi(ConverterWidget)
        QtCore.QMetaObject.connectSlotsByName(ConverterWidget)
        ConverterWidget.setTabOrder(self.cbFromCurrency, self.tfFromCurrency)
        ConverterWidget.setTabOrder(self.tfFromCurrency, self.cbToCurrency)
        ConverterWidget.setTabOrder(self.cbToCurrency, self.tfConvertResult)

    def retranslateUi(self, ConverterWidget):
        _translate = QtCore.QCoreApplication.translate
        ConverterWidget.setWindowTitle(_translate("ConverterWidget", "Currency Converter"))
        self.tfConvertResult.setText(_translate("ConverterWidget", "0,00"))
        self.btShowTable.setText(_translate("ConverterWidget", "Table Mata Uang"))
        self.btRefresh.setText(_translate("ConverterWidget", "Refresh"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ConverterWidget = QtWidgets.QWidget()
    ui = Ui_ConverterWidget()
    ui.setupUi(ConverterWidget)
    ConverterWidget.show()
    sys.exit(app.exec_())
