# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Table2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 420)
        MainWindow.setMinimumSize(QtCore.QSize(800, 420))
        MainWindow.setMaximumSize(QtCore.QSize(800, 420))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 40, 691, 281))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btShowTable = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btShowTable.setObjectName("btShowTable")
        self.gridLayout_2.addWidget(self.btShowTable, 4, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cbFromCurrency = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cbFromCurrency.setObjectName("cbFromCurrency")
        self.horizontalLayout_2.addWidget(self.cbFromCurrency)
        self.tfFromCurrency = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tfFromCurrency.sizePolicy().hasHeightForWidth())
        self.tfFromCurrency.setSizePolicy(sizePolicy)
        self.tfFromCurrency.setMaximum(99999999.99)
        self.tfFromCurrency.setObjectName("tfFromCurrency")
        self.horizontalLayout_2.addWidget(self.tfFromCurrency)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.cbToCurrency = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cbToCurrency.setObjectName("cbToCurrency")
        self.horizontalLayout_2.addWidget(self.cbToCurrency)
        for row in self.dataTable:
            self.cbToCurrency.addItem(row[1])
            self.cbFromCurrency.addItem(row[1])                                     #
        self.tfConvertResult = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.tfConvertResult.setReadOnly(True)
        self.tfConvertResult.setObjectName("tfConvertResult")
        self.horizontalLayout_2.addWidget(self.tfConvertResult)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 4, 0, 1, 1)
        self.btSwap = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btSwap.setObjectName("btSwap")
        self.gridLayout_2.addWidget(self.btSwap, 4, 2, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.gridLayoutWidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout_2.addWidget(self.tableWidget, 5, 0, 1, 3)
        self.tableWidget.hide()                                                     #
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 28))
        self.menubar.setObjectName("menubar")
        self.menuConvert = QtWidgets.QMenu(self.menubar)
        self.menuConvert.setObjectName("menuConvert")
        self.menuTable = QtWidgets.QMenu(self.menubar)
        self.menuTable.setObjectName("menuTable")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuConvert.menuAction())
        self.menubar.addAction(self.menuTable.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btShowTable.setText(_translate("MainWindow", "Tabel"))
        self.label.setText(_translate("MainWindow", "to"))
        self.tfConvertResult.setText(_translate("MainWindow", "0,00"))
        self.btSwap.setText(_translate("MainWindow", "Tukar"))
        self.menuConvert.setTitle(_translate("MainWindow", "Convert"))
        self.menuTable.setTitle(_translate("MainWindow", "Table"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
