# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Table.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TableWidget(object):
    def setupUi(self, TableWidget):
        TableWidget.setObjectName("TableWidget")
        TableWidget.resize(820, 422)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TableWidget.sizePolicy().hasHeightForWidth())
        TableWidget.setSizePolicy(sizePolicy)
        self.verticalLayoutWidget = QtWidgets.QWidget(TableWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 50, 761, 331))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.btUpdateDB = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btUpdateDB.setObjectName("btUpdateDB")
        self.horizontalLayout_4.addWidget(self.btUpdateDB)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tfCurrencyCode = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tfCurrencyCode.sizePolicy().hasHeightForWidth())
        self.tfCurrencyCode.setSizePolicy(sizePolicy)
        self.tfCurrencyCode.setMinimumSize(QtCore.QSize(50, 0))
        self.tfCurrencyCode.setObjectName("tfCurrencyCode")
        self.horizontalLayout.addWidget(self.tfCurrencyCode)
        self.tfCurrencyValue = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.tfCurrencyValue.setMinimumSize(QtCore.QSize(150, 0))
        self.tfCurrencyValue.setDecimals(5)
        self.tfCurrencyValue.setMaximum(9999999.99)
        self.tfCurrencyValue.setObjectName("tfCurrencyValue")
        self.horizontalLayout.addWidget(self.tfCurrencyValue)
        self.btSave = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btSave.sizePolicy().hasHeightForWidth())
        self.btSave.setSizePolicy(sizePolicy)
        self.btSave.setObjectName("btSave")
        self.horizontalLayout.addWidget(self.btSave)
        self.btDelete = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btDelete.sizePolicy().hasHeightForWidth())
        self.btDelete.setSizePolicy(sizePolicy)
        self.btDelete.setObjectName("btDelete")
        self.horizontalLayout.addWidget(self.btDelete)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.tableWidget)

        self.retranslateUi(TableWidget)
        QtCore.QMetaObject.connectSlotsByName(TableWidget)

    def retranslateUi(self, TableWidget):
        _translate = QtCore.QCoreApplication.translate
        TableWidget.setWindowTitle(_translate("TableWidget", "Currencies Data"))
        self.btUpdateDB.setText(_translate("TableWidget", "Update database"))
        self.btSave.setText(_translate("TableWidget", "Simpan"))
        self.btDelete.setText(_translate("TableWidget", "Hapus"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("TableWidget", "Kode Mata Uang"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("TableWidget", "Nilai Mata Uang"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TableWidget = QtWidgets.QWidget()
    ui = Ui_TableWidget()
    ui.setupUi(TableWidget)
    TableWidget.show()
    sys.exit(app.exec_())
